"use client";
import React, { useEffect, useRef } from "react";
import { Inter } from "next/font/google";
import "/public/font/stylesheet.css";
import "./globals.css";
import { ReactLenis, useLenis } from "lenis/react";
import { usePathname } from "next/navigation";
// import Lenis from "@/dist/lenis.mjs";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });
import { CustomHead } from '@/components/custom-head/index'
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ seo = { title: '', description: '', image: '', keywords: '' }, children }) {
  const lenis = useLenis(({ scroll }) => {});
  const pathname = usePathname();
  useEffect(() => {
    const whiteSections = document.querySelectorAll(".section-white");
    const whitespSections = document.querySelectorAll(".section-whitesp");
    const beigeSections = document.querySelectorAll(".section-beige");
    whiteSections.forEach((section) => {
      ScrollTrigger.create({
        trigger: section,
        start: "-30% top",
        end: "bottom top",
        // markers: true,
        onEnter: () =>
          document.querySelector("header").classList.add("text-black"),
        onLeaveBack: () =>
          document.querySelector("header").classList.remove("text-black"),
        onEnterBack: () =>
          document.querySelector("header").classList.add("text-black"),
        onLeave: () =>
          document.querySelector("header").classList.remove("text-black"),
      });
    });
    whitespSections.forEach((section) => {
      ScrollTrigger.create({
        trigger: section,
        start: "top top",
        end: "bottom top",
        // markers: true,
        onEnter: () =>
          document.querySelector("header").classList.add("text-black"),
        onLeaveBack: () =>
          document.querySelector("header").classList.remove("text-black"),
        onEnterBack: () =>
          document.querySelector("header").classList.add("text-black"),
        onLeave: () =>
          document.querySelector("header").classList.remove("text-black"),
      });
    });

    beigeSections.forEach((section) => {
      ScrollTrigger.create({
        trigger: section,
        start: "top top",
        end: "bottom top",
        // markers: true,
        onEnter: () =>
          document.querySelector("header").classList.add("text-beige"),
        onLeaveBack: () =>
          document.querySelector("header").classList.remove("text-beige"),
        onEnterBack: () =>
          document.querySelector("header").classList.add("text-beige"),
        onLeave: () =>
          document.querySelector("header").classList.remove("text-beige"),
      });
    });
  }, []);
  const headerClasses = {
    "/": "header header-home",
    "/work": "header header-work",
    "/studio": "header header-studio",
    "/news": "header header-news",
    "/contact": "header header-contact",
  };
  const headerClass = headerClasses[pathname] || "header";
  return (
    <ReactLenis root>
      <html lang="en">
      <CustomHead {...seo} />
        <body className={inter.className}>
          <Header className={headerClass} />
          <main className="main">{children}</main>
          <Footer />
        </body>
      </html>
    </ReactLenis>
  );
}
